name: "Build Deploy and Test"

on:
  push:
    branches:
      - main
      - demo
      
env:
  CUSTOMER_PROJECT: './src/CustomerSite/CustomerSite.csproj'
  PUBLISHER_PROJECT: './src/AdminSite/AdminSite.csproj'
  SERVICES_TEST_PROJECT: './src/Services.Test/Services.Test.csproj'
  UI_TEST_PROJECT: './src/UI.Test/UI.Test.csproj'
  CUSTOMER_AZURE_WEBAPP_PACKAGE_PATH: './src/Marketplace.SaaS.Accelerator.CustomerSite/publish'
  PUBLISHER_AZURE_WEBAPP_PACKAGE_PATH: './src/Marketplace.SaaS.Accelerator.AdminSite/publish'
  DOTNET_CORE_VERSION: '6.0.x'
  
jobs:
  deploytocustomer:
    name: Deploy customer app
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'deploy-prod' || 'deploy' }}
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }} 
    
    - name: Build app
      run: |
        dotnet build ${{ env.CUSTOMER_PROJECT }} --configuration Release
        dotnet publish ${{ env.CUSTOMER_PROJECT }} --configuration Release --no-build --output ${{ env.CUSTOMER_AZURE_WEBAPP_PACKAGE_PATH }}
    
    - name: Unit Test
      run: dotnet test ${{ env.SERVICES_TEST_PROJECT }}
      
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_CUSTOMER_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_CUSTOMER_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.CUSTOMER_AZURE_WEBAPP_PACKAGE_PATH }}
  
  deploytopublisher:
    name: Deploy publisher app
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'deploy-prod' || 'deploy' }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }} 
        
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Build app
      run: |
        dotnet build ${{ env.PUBLISHER_PROJECT }} --configuration Release
        dotnet publish ${{ env.PUBLISHER_PROJECT }} --configuration Release --no-build --output ${{ env.PUBLISHER_AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_PUBLISHER_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISHER_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.PUBLISHER_AZURE_WEBAPP_PACKAGE_PATH }}
